version: '3'

services:
  livebook:
    image: livebook/livebook
    ports:
      - '8080:8080'
    working_dir: '/programming_machine_learning'
    volumes:
        - ./:/programming_machine_learning
    environment:
      - LIVEBOOK_HOME=/programming_machine_learning
      - LIVEBOOK_DEFAULT_RUNTIME=standalone
